# Generated by Django 4.1.3 on 2022-12-03 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='born_date',
        ),
        migrations.RemoveField(
            model_name='family',
            name='surname',
        ),
    ]
