# Generated by Django 4.1.3 on 2022-12-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTest', '0003_family_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='born_year',
            field=models.IntegerField(null=True),
        ),
    ]
