# Generated by Django 4.1.3 on 2022-12-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTest', '0004_family_born_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='born_year',
        ),
        migrations.AddField(
            model_name='family',
            name='born_date',
            field=models.DateField(null=True),
        ),
    ]
